version: '3'
services:
  nginx:
    build: nginx
    ports:
      - "8080:8080"
  envoy:
    build: envoy
    ports:
      - "8090:8090"
  load-tester:
    build: load-tester
    # Done intentionally, launch the tester via `./run_load_tester.sh`
    entrypoint: "false"
